### ISSUE TITLE
Safari Private Browsing

### ISSUE THREAD

**Issue by davyboyhayes** [tiaanduplessis/stoor#2]
A bit of a standard PITA for Safari Private Browsing. Any attempt to set on localStorage in Private Browsing, causes a "QuotaExceededError" to occur:

```
var things = new Stoor({namespace: 'localStorage'});
try{
   things.set('hi','bye');
} catch(e){
   console.log(e);
}
```
QuotaExceededError (DOM Exception 22): The quota has been exceeded.

**Comment by tiaanduplessis** [comment]
Should be resolved with 1.0.2
